### PR TITLE
Todo list project development

### PR DESCRIPTION
**Pull request by nurislam-ab**
Following functionality developed for this project

- [x] Developed Project and Todo models
- [x] Developed controller, view, storage factories to handle the logic of the app, to render the views, and store the data in the local storage of the browser
- [x] Implemented CRUD for the projects and todos
- [x] Developed design inspired by the Trello app

### CODE REVIEW

**Comment by nurislam-ab** [comment]
For some reason, I cannot enable GitHub actions for this repo. I have read [here](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository) how to enable the checks for the forked repo, but I don't have an [option ](http://joxi.ru/vAWPRzViOlG0jr) that could enable checks for the forked repo

**Comment by nurislam-ab** [comment]
Placing the [link ](http://joxi.ru/nAylp1KUj8DPY2) to the screenshot for the checks in the local repo.

**Review by wathigo — CHANGES_REQUESTED** [review]
### Changes Required.
Great job on this project.

**REQUIRED**
*  There is a 'default' project. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list)).

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

**Pull request merged**
